### ISSUE TITLE
Missing Sc2 screens and detection of in game status (Alt+Tab; in/out)

### ISSUE THREAD

**Issue by propagare** [teampheenix/StarCraft-Casting-Tool#3]
Hello, :)

are you maybe willing to extend your great tool to the status which the SC2 client can switch to as well? 

If so it would be also really great if you also find the possibility in the Windows API to detect if someone is in or out tabbed (ALT+Tab) of Starcraft 2 (-->Define a scene?) but I didn't found anything regarding to this in the Sc2 API. 

These are all SC2 screens I found via http://localhost:6119/ui

1. Startup, loading and leaving Sc2
2. Login screen (name, region, password, offline)
3. In menu after Login (Home screen)
4. Campaign screen
5. Coop screen
6. Custom Games main screen
7. Multiplayer: Training, Versus AI, Unranked, Ranked and Testing (Ranked ladder screen)
8. Tournament screen
9. Custom game Lobby
10. Arcade screen (join)
11. Arcade screen (browse)
12. Arcade game Lobby
13. Collection screen
14. Replay browsing
15. Replay "Watch With Others" Lobby
16. Score screen after a Custom game
17. Score screen after a Multiplayer Ranked
18. Score screen after Arcade

These following are all screens I found via http://localhost:6119/game
which are additional needed to verify your are in a replay and not in game.

In an Arcade replay
In a Replay
2v2 In game: 
2v2 In Replay
3v3 In game
3v3 In Replay
4v4 In game
4v4 Replay
In game Coop

I can see" ~18 drop down menus, filled or empty (to switch to a default screen or do nothing) with OBS studio scenes filled by the users. :)

The ethical imperative says: Act in such a way that you have more room for actions after your decision (~Dr. Heinz von Forster). This motivates people and it isn't focused on problem solving! :)

What do you think about this?  I could provide all necessary logical gates from the API client to filter for these status. :)

**Comment by 2press** [comment]
Hi,

I don't think that I really get what you want to propose here. Please try to rephrase
> are you maybe willing to extend your great tool to the status which the SC2 client can switch to as well?

and/or elaborate on it.

The tool is already listing to http://localhost:6119/ui and http://localhost:6119/game to toggle the production tab and set the ingame score.  Furthermore it detects for the same purpose wether SC2 is the active window in foreground (or tabbed out).

**Comment by 2press** [comment]
If you are looking for a scene switcher for OBS, take a look here:
https://github.com/leigholiver/OBS-SC2Switcher

**Comment by propagare** [comment]
Hi, 
I would like to see you implement all missing Sc2 scenes which I listed above. Both groups.
I would chip in a small donation if you extend the number (three atm) of your already existing drop down menus for scenes. 

I have extracted and could provide you the exact spelling of the Sc2 scenes.

**Comment by 2press** [comment]
You are mistaking StarCraft Casting Tool with a scene switcher - this tool doesn't have the drop down menu or functionality you are taking about.
