### ISSUE TITLE
Translation to French (and Russian)

### ISSUE THREAD

**Issue by 2press** [teampheenix/StarCraft-Casting-Tool#4]
### French
I am looking for anyone that could help to translate StarCraft Casting Tool to French. 

You would need to translate every `msgid` in https://github.com/teampheenix/StarCraft-Casting-Tool/blob/master/locales/fr_FR/LC_MESSAGES/messages.po to French, e.g.,
 https://github.com/teampheenix/StarCraft-Casting-Tool/blob/719f98a59c5a3bfc7395686ad95bf3f6ffacf098/locales/fr_FR/LC_MESSAGE/messages.po#L19-L20

This can be done either in the raw po-file or via https://poedit.net/. It doesn't need to be done by somebody alone - even translating a single sentence or string is appreciated. 

###  Russian
~~Similarly I am looking for someone to check and refine existing translations to Russian that were done via Google Translator. These can be found in~~

https://github.com/teampheenix/StarCraft-Casting-Tool/blob/master/locales/ru_RU/LC_MESSAGES/messages.po

~~and are marked with a comment like `Needs to be checked by a Russian`, for example~~

https://github.com/teampheenix/StarCraft-Casting-Tool/blob/719f98a59c5a3bfc7395686ad95bf3f6ffacf098/locales/ru_RU/LC_MESSAGES/messages.po#L662-L667

~~If you have checked or refined a translation, simple remove the comment.~~

~~This can be done either in the raw po-file or via https://poedit.net/. It doesn't need to be done by somebody alone - even checking or refining a single sentence or string is appreciated.~~ 

Completed in https://github.com/teampheenix/StarCraft-Casting-Tool/pull/5.

### Discord

If you have any questions please feel free to contact me via Discord https://discord.gg/G9hFEfh

**Comment by 2press** [comment]
There have been a lot of changes due the upcoming v2.0 release. I have updated the Russian localization accordingly with the help of Google Translate, but it might to be checked by a Russian native speaker: 

https://github.com/teampheenix/StarCraft-Casting-Tool/blob/master/locales/ru_RU/LC_MESSAGES/messages.po

**Comment by remram44** [comment]
The correct link seems to be https://github.com/teampheenix/StarCraft-Casting-Tool/blob/master/locales/fr_FR/LC_MESSAGES/messages.po (LC_MESSAGE**S**)

**Comment by 2press** [comment]
@remram44 Thank you! I have fixed the link.
